name: Deploy to Cloudflare Pages
on:
    push:
        paths:
            - Docs/**
            - GameLogic/**
            - .github/workflows/cloudflare-deploy-docs.yml

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Install doxygen
        run: sudo apt update && sudo apt install doxygen

      - name: Generate site
        working-directory: memory-game/Docs/
        run: doxygen Doxyfile-logic

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy /home/runner/work/memory-game/memory-game/Docs/html/ --project-name=memorygame-docs